# Generated by Django 3.2 on 2023-03-17 10:42

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_pictures_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='pictures/', verbose_name='Picture'),
        ),
    ]
