# Generated by Django 3.2 on 2023-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20230317_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='picture_url',
            field=models.URLField(default='https://oaidalleapiprodscus.blob.core.windows.net/private/org-gFQStLnte2d45HbTKeHdFYOr/user-YXp2DpA29SXrTdG5bGu5dHhP/img-AJlnCJaPHy8qThpa89PPIklt.png?st=2023-03-18T06%3A22%3A11Z&se=2023-03-18T08%3A22%3A11Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-03-18T00%3A40%3A27Z&ske=2023-03-19T00%3A40%3A27Z&sks=b&skv=2021-08-06&sig=zIC%2BZsqQTm1PkdyfCHdAwnYdUWhQA2y9CR%2BufZb5UO4%3D', max_length=1000),
            preserve_default=False,
        ),
    ]
